paths:
  raw_data: "data/raw"
  processed_data: "data/processed"
  external_data: "data/external"
  models: "models"

api_keys:
  agmarknet: "" # Placeholder if needed, usually open
  open_meteo: "" # Open access, no key needed usually
  gov_data: "579b464db66ec23bdd000001795acca069e747436daf7b98bf6a3024" # API key for data.gov.in

region:
  state: "Telangana"
  districts:
    - "Warangal"
    - "Karimnagar"
    - "Nalgonda"
    - "Khammam"
    - "Nizamabad"

commodities:
  - "Rice"
  - "Maize"
  - "Cotton"
  - "Red Gram" # Tur
